version: '3.8'
services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
      #порты можно не указывать, поскольку подключаться будем не с локалхоста, а из другого контейнера
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=second
      - POSTGRES_PASSWORD=admin
    volumes:
      - "db-data:/var/lib/postgresql/data"
      #- ./data:/docker-entrypoint-initdb.d

  app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/second
      - JS_URL=http://localhost
    image: 'second-playground'
    ports:
      - 8083:8083
    depends_on:
      - postgres

volumes:
  db-data: